services:
  - type: web
    name: glossy-pos-backend
    runtime: docker
    plan: free
    region: singapore
    healthCheckPath: /health/ready
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: FRONTEND_ORIGIN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_BUCKET_PRIVATE
        sync: false
      - key: AWS_S3_KMS_KEY_ID
        sync: false
      - key: ORDER_NUMBER_TIMEZONE
        value: Asia/Bangkok
      - key: COMPANY_THAI_NAME
        value: กรอสซี่ ปริ้น แอนด์ พรีเมี่ยม
      - key: COMPANY_ENGLISH_NAME
        value: GLOSSY PRINT AND PREMIUM
      - key: COMPANY_BRANCH_NO
        value: สำนักงานใหญ่
      - key: COMPANY_ADDRESS
        value: 55 ถนนศรีนครินทร์ แขวงหนองบอน เขตประเวศ จังหวัดกรุงเทพฯ 10250
      - key: COMPANY_PHONE
        value: 081-555-2929
      - key: COMPANY_TAX_ID
        value: '3160100252587'
